"""The project registry — derived from the `project.md` anchors.

Each project folder holds a `project.md` (kind: project) declaring the canonical
id (PRJ-NNN-CODE), the code, name, sponsor, and status. `projects.yaml` at the
repo root is the generated index of them all.
"""
from __future__ import annotations

from collections import Counter
from pathlib import Path

import yaml

from .loader import load

DOCUMENTS_DIR = Path("documents")
_FIELDS = ("id", "code", "name", "sponsor", "status")


def load_projects(documents_dir: str | Path = DOCUMENTS_DIR) -> list[dict]:
    """Every project anchor (kind: project), sorted by id."""
    projects = []
    for path in sorted(Path(documents_dir).rglob("*.md")):
        try:
            doc = load(path)
        except ValueError:
            continue
        if doc.kind == "project":
            entry = {k: str(doc.frontmatter.get(k, "")) for k in _FIELDS}
            entry["path"] = doc.path
            projects.append(entry)
    projects.sort(key=lambda p: p["id"])
    return projects


def registry_issues(projects: list[dict]) -> list[str]:
    """Cross-project validation: ids and codes must be unique."""
    issues = []
    for field in ("id", "code"):
        dups = [v for v, n in Counter(p[field] for p in projects).items() if v and n > 1]
        issues += [f"duplicate project {field}: {d}" for d in dups]
    return issues


def render_yaml(projects: list[dict]) -> str:
    data = [{k: p[k] for k in _FIELDS} for p in projects]
    header = ("# Generated by `docunit projects` — do not edit.\n"
              "# The project.md anchors under documents/ are the source of truth.\n")
    return header + yaml.safe_dump({"projects": data}, sort_keys=False, allow_unicode=True)
